# -*- coding: utf-8 -*-
"""fruits-fresh-CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_BOHguIhLFyu11uAgM2pjUepo6Nr4mWn
"""

import warnings
warnings.filterwarnings(
    "ignore",
    message='Field "model_name" has conflict with protected namespace "model_".*',
)

import os
import mlflow
import mlflow.tensorflow
import tensorflow as tf

# ---------------- MLflow ----------------

def configure_mlflow():
    mlflow.set_tracking_uri("http://127.0.0.1:5001")
    mlflow.set_experiment("fruit-freshness")

    print("Tracking URI :", mlflow.get_tracking_uri())
    print("Experiment   :", mlflow.get_experiment_by_name("fruit-freshness"))

# -------------- Project Paths ----------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

LOCAL_DATA_ROOT = os.path.join(PROJECT_ROOT, "dataset")

# Configure MLflow
configure_mlflow()

# Image settings
img_height = 224
img_width = 224
batch_size = 32


def _is_valid_split_dir(path):
    if not os.path.isdir(path):
        return False

    for entry in os.listdir(path):
        class_dir = os.path.join(path, entry)
        if not os.path.isdir(class_dir):
            continue

        for current_root, _, file_names in os.walk(class_dir):
            if any(
                file_name.lower().endswith(
                    (".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp")
                )
                for file_name in file_names
            ):
                return True

    return False





def load_dataset_root():
    train_path = os.path.join(LOCAL_DATA_ROOT, "train")
    test_path = os.path.join(LOCAL_DATA_ROOT, "test")

    if not os.path.isdir(train_path):
        raise FileNotFoundError(f"Train folder not found: {train_path}")

    if not os.path.isdir(test_path):
        raise FileNotFoundError(f"Test folder not found: {test_path}")

    print("Using Local Dataset")
    print("Train:", train_path)
    print("Test :", test_path)

    return train_path, test_path

train_path, test_path = load_dataset_root()

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_path,
    image_size=(img_height, img_width),
    batch_size=batch_size,
    seed=123,
    validation_split=0.2,
    subset='training'
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    train_path,
    image_size=(img_height, img_width),
    batch_size=batch_size,
    seed=123,
    validation_split=0.2,
    subset='validation'
)

orginal_class_name_for_display=train_ds.class_names
orginal_class_name_for_dis=val_ds.class_names

def normalize(image,label):
  image=tf.cast(image/255. ,tf.float32)
  return image,label

train_ds=train_ds.map(normalize)
val_ds=val_ds.map(normalize)

print("Image dataset lable and normalized successfully.")
print(f"Number of batches in normalized training dataset:{tf.data.experimental.cardinality(train_ds).numpy()}")
print(f"Numpy of batches in normalized validation dataset:{tf.data.experimental.cardinality(val_ds).numpy()}")
print(f"Image Size:{img_height}*{img_width}")
print(f"Batch size:{batch_size}")

def map_binary(image,label):
    binary_label=tf.cast(label>=len(orginal_class_name_for_display)//2,tf.float32)
    return image,binary_label

train_ds = train_ds.map(map_binary)
val_ds = val_ds.map(map_binary)

data_augmentation=tf.keras.Sequential([
    tf.keras.layers.RandomFlip('horizontal'),
    tf.keras.layers.RandomRotation(0.2),
    tf.keras.layers.RandomZoom(0.2)
])
def augment(image,label):
  image=data_augmentation(image)
  return image,label

train_ds_augmentaion=train_ds.map(augment)

model=tf.keras.Sequential([

    tf.keras.layers.Input(shape=(img_height,img_width,3)),

    tf.keras.layers.Conv2D(32,(3,3),activation='relu'),
    tf.keras.layers.MaxPooling2D((2,2)),

    tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
    tf.keras.layers.MaxPooling2D((2,2)),

    tf.keras.layers.Conv2D(128,(3,3),activation='relu'),
    tf.keras.layers.MaxPooling2D((2,2)),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
epochs = 20

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

with mlflow.start_run(run_name="CNN_Fruit_Classification"):
    run = mlflow.active_run()

    print("Run ID :", run.info.run_id)
    print("Experiment :", mlflow.get_experiment_by_name("fruit-freshness"))

    # Parameters
    mlflow.log_param("Image Height", img_height)
    mlflow.log_param("Image Width", img_width)
    mlflow.log_param("Batch Size", batch_size)
    mlflow.log_param("Epochs", epochs)
    mlflow.log_param("Optimizer", "Adam")
    mlflow.log_param("Loss", "Binary Crossentropy")
    mlflow.log_param("Architecture", "Custom CNN")

    history = model.fit(
        train_ds_augmentaion,
        validation_data=val_ds,
        epochs=epochs,
        callbacks=[early_stopping]
    )

    # Log training metrics
    for epoch in range(len(history.history["loss"])):
        mlflow.log_metric("train_loss", history.history["loss"][epoch], step=epoch)
        mlflow.log_metric("train_accuracy", history.history["accuracy"][epoch], step=epoch)
        mlflow.log_metric("val_loss", history.history["val_loss"][epoch], step=epoch)
        mlflow.log_metric("val_accuracy", history.history["val_accuracy"][epoch], step=epoch)

    test_ds=tf.keras.utils.image_dataset_from_directory(
        test_path,
        image_size=(img_height,img_width),
        batch_size=batch_size,
        shuffle=False
    )

    test_ds=test_ds.map(normalize)
    test_ds=test_ds.map(map_binary)
    loss,accuracy=model.evaluate(test_ds)
    mlflow.log_metric("test_loss", float(loss))
    mlflow.log_metric("test_accuracy", float(accuracy))
    test_loss=loss
    test_accuracy=accuracy
    print(f"Test loss:{test_loss}")
    print(f"Test accuracy:{test_accuracy}")

    os.makedirs("models", exist_ok=True)

    model_path = "models/Fruit_classification_model.keras"

    model.save(model_path)

    mlflow.tensorflow.log_model(
        model=model,
        name="cnn_model"
    )

    mlflow.log_artifact(model_path)

    print("Model Logged Successfully")