services:
    mlflow:
        image: ghcr.io/mlflow/mlflow:v2.10.0
        command: mlflow ui --host 0.0.0.0 --port 5001
        ports:
            - "5001:5001"

    backend:
        image: prashanttech/fresh-rotten:backend-arm64-1.0
        platform: linux/arm64
        environment:
            - MODEL_PATH=/app/models/Fruit_classification_model.h5
        ports:
            - "8000:8000"


    frontend:
        build:
            context: ..
            dockerfile: docker/frontend.dockerfile
        environment:
            - API_URL=http://backend:8000
        ports:
            - "8501:8501"
        depends_on:
            - backend
